name: Web CI/CD
on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  CI:
    name: Integration
    uses: ./.github/workflows/web-ci.yml

  CD:
    name: Deployment
    uses: ./.github/workflows/web-cd.yml
    needs: CI
    permissions:
      checks: write
      pull-requests: write
    with:
      environment: ${{ github.event_name == 'push' && github.ref_name == 'master' && 'prod' || 'staging' }}
      channelId: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || 'live'}}
    secrets: inherit
